[package]
name = "wd-gpui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
wd-core = { workspace = true }
wd-shell = { path = "../wd-shell" }
wd-waydroid = { path = "../wd-waydroid" }
gpui-kit = "0.6"
tracing.workspace = true

[lints]
workspace = true

[[bin]]
name = "wd-gpui"
path = "src/bin/wd-gpui.rs"
